### ISSUE TITLE
Another library instead of pi_piper?

### ISSUE THREAD

**Issue by jvlobo** [fernandofussuma/CharLcd-ruby-raspberry-pi#1]
I've noticed **pi_piper** is discontinued.

Do you think the LCD could work with another library, such [rpi_gpio](https://github.com/ClockVapor/rpi_gpio) ??

Thanks.

**Comment by jvlobo** [comment]
I've changed the library from pi_piper to rpi_gpio -> https://github.com/jvlobo/CharLcd-ruby-raspberry-pi/commit/a09d263f434a9d808fd7328e052655be2864933f

If you like it I can pull request to your repo, if not, no problem :)

**Comment by fernandofussuma** [comment]
Sure,
Since I don't have a raspberry right now to test it, just confirm it's working fine.
Thanks,

**Comment by jvlobo** [comment]
Great.

I've tested it a little bit more and everything looks like it works perfectly with the new library.

https://github.com/fernandofussuma/CharLcd-ruby-raspberry-pi/pull/3

As soon as you integrate the changes and update the gem in rubygem.org I'll update my local gem repository and test it again :)

Thanks.

**Comment by fernandofussuma** [comment]
Thank you!!!
=]

**Comment by jvlobo** [comment]
@fernandofussuma I think it's also necessary to update **Gemfile.lock** file, but I'm not sure how it has to be

**Comment by fernandofussuma** [comment]
Gemfile.lock, shouldn't be there. =P
Made some changes and uploaded to ruby gems, added thanks to readme too!

**Comment by jvlobo** [comment]
awesome!! thanks :)
